export { seals };

const seals = [
  {
    names: snorber,
    age: 5,
    weight: 350,
    gender: male,
    hostile: no,
    species: grayseal,
    value: 1500,
    stock: 1,
  },
  {
    names: blobbers,
    age: 7,
    weight: 275,
    gender: male,
    hostile: no,
    species: ringedseal,
    value: 1700,
    stock: 1,
  },
  {
    names: floofer,
    age: 6,
    weight: 225,
    gender: female,
    hostile: no,
    species: harpseal,
    value: 1600,
    stock: 1,
  },
  {
    names: chonker,
    age: 14,
    weight: 820,
    gender: male,
    hostile: yes,
    species: leopardseal,
    value: 3950,
    stock: 1,
  },
  {
    names: bubba,
    age: 16,
    weight: 9001,
    gender: male,
    hostile: yes,
    species: elephantseal,
    value: 7800,
    stock: 1,
  },
  {
    names: tusky,
    age: 17,
    weight: 3500,
    gender: female,
    hostile: yes,
    species: walrus,
    value: 5400,
    stock: 1,
  },
  {
    names: snoofer,
    age: 10,
    weight: 250,
    gender: male,
    hostile: no,
    species: ribbonseal,
    value: 2200,
    stock: 1,
  },
  {
    names: flopper,
    age: 9,
    weight: 660,
    gender: female,
    hostile: no,
    species: grayseal,
    value: 2600,
    stock: 1,
  },
  {
    names: borker,
    age: 13,
    weight: 450,
    gender: male,
    hostile: no,
    species: furseal,
    value: 2650,
    stock: 1,
  },
  {
    names: skeeter,
    age: 18,
    weight: 600,
    gender: male,
    hostile: no,
    species: sealion,
    value: 3200,
    stock: 1,
  },
  {
    names: honker,
    age: 19,
    weight: 1050,
    gender: male,
    hostile: yes,
    species: leopardseal,
    value: 4250,
    stock: 1,
  },
  {
    names: skipper,
    age: 7,
    weight: 200,
    gender: male,
    hostile: no,
    species: harborseal,
    value: 1450,
    stock: 1,
  },
];
